---

version: '3'

services:
  pg:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: escuela
      POSTGRES_DB: escuela
    volumes:
       - ./escuela.sql:/docker-entrypoint-initdb.d/escuela.sql
